### PR TITLE
[Feature] Expose port property

### PR DESCRIPTION
**Pull request by KabaDH**
Issue Description:
Some trackers does not accept port 0 in announce request.

What is the fix:
- [x]  Exposed "port" property for TorrentTask, TorrentStream, MetadataDownloader.

Additional info:
- [x] upgraded linter to 3.0.0
- [x] code cosmetic refractoring to follow up the linter`s rules.

### CODE REVIEW

**Comment by KabaDH** [comment]
Hello @moham96 ! Here is a small PR for the review.

**Comment by moham96** [comment]
1- We are not announcing 0 as a port, passing 0 as a port simply chooses the first free port it finds as stated by dart documentation:

> If [port] has the value 0 an ephemeral port will be chosen by the system. The actual port used can be retrieved using the [port] getter.

, and then we announce that port to the tracker, or have you noticed announces with 0 as a port ?

2- I'm not sure about changing the constants to camel case, i know it is the style of dart code but AFAIK it has an exception if the code is already using the upper case form or if the constants appear in some specifications.

In existing code that uses ALL_CAPS_WITH_UNDERSCORES for constants, you may continue to use all caps to stay consistent. https://dart.dev/tools/linter-rules/constant_identifier_names

**Comment by KabaDH** [comment]
> 1- We are not announcing 0 as a port, passing 0 as a port simply chooses the first free port it finds as stated by dart documentation:
> 
> > If [port] has the value 0 an ephemeral port will be chosen by the system. The actual port used can be retrieved using the [port] getter.
> 
> , and then we announce that port to the tracker, or have you noticed announces with 0 as a port ?

Maybe it works somewhere, but our announce on server side sees 0 port on getting request from the client. Also, [this tracker](http://nyaa.tracker.wf:7777/announce) force to us to deal with exception on our request to announce with default port = 0.
So, I exposed it as an optional parameter to use, when you need it.

> 2- I'm not sure about changing the constants to camel case, i know it is the style of dart code but AFAIK it has an exception if the code is already using the upper case form or if the constants appear in some specifications.
> 
> In existing code that uses ALL_CAPS_WITH_UNDERSCORES for constants, you may continue to use all caps to stay consistent. https://dart.dev/tools/linter-rules/constant_identifier_names

Up to you. ALL_CAPS_WITH_UNDERSCORES helps us easier to deal with global variables as their naming much differ from local variables in lowerCamelCase. But in not "Dart way".
I can revert this commit, if you wish.

**Comment by moham96** [comment]
> Maybe it works somewhere, but our announce on server side sees 0 port on getting request from the client.

did you debug it and found this problem? do you have a reproducible code? a wireshark capture? because if the announce is arriving to the tracker with port=0 then we might have some async problem in the code and in that case even passing an explicit port may not be enough.


also please rebase the PR on optimization branch (only the first commit)

**Comment by KabaDH** [comment]
I will put it in draft for now. I can't reproduce that tracker exception, and it's strange. 
The problem was that on the first request to the announce, the options contained port=0 and I got an exception, then a connection reset from the tracker. Only manually selecting a port in options helped to get the data. But now, it accepts the first request with port=0, and on the further requests, we have the correct port in the options. 
1st request:

2nd:

**Comment by moham96** [comment]
Are you using `MetadataDownloader` class because it does seem that we are sending 0 as a port https://github.com/moham96/dtorrent_task/blob/c87eb30ca93b80a45678113794286f18405b7336/lib/src/metadata/metadata_downloader.dart#L365

but this is a symptom of a much bigger problem, it seems that the `MetadataDownloader` is not handling incoming connections at all (i.e we are not listening for connections) unlike the `TorrentTask` class which does listen for connections, in that case simply passing the port number in the announce is not enough because no peers will be able to connect to us, only we can connect to them,

This can be fixed in the `MetadataDownloader` class but what i want to do is refactor the `MetadataDownloader` and `TorrentTask` class to reduce code duplication, we should extract similar code in some mixin or a class

**Comment by KabaDH** [comment]
Yes, I use MetadataDownloader.
It would be really nice to get rid of code duplication  across MetadataDownloader and TorrentTask.
Anyway, port=0 works, so its not a big issue.

**Pull request closed without merging**
